# Generated by Django 4.2.6 on 2024-02-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='name',
        ),
    ]
