# Generated by Django 4.2.6 on 2024-02-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebForm', '0002_rename_location_name_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_name',
            new_name='name',
        ),
    ]
