# Generated by Django 5.0.1 on 2024-02-29 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebForm', '0004_site_unique_name_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('number_in_household', models.IntegerField()),
                ('street_address', models.TextField()),
                ('zip_code', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebForm.site')),
            ],
        ),
    ]
