# Generated by Django 5.0.1 on 2024-03-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebForm', '0007_field_field_id_field_name_field_tefap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='field',
            name='tefap',
            field=models.BooleanField(),
        ),
    ]
