# Generated by Django 5.0.1 on 2024-04-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebForm', '0012_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
