# Generated by Django 4.2.11 on 2024-04-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebForm', '0014_passwordcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordcode',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='passwordcode',
            name='generation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
