# Generated by Django 4.2.11 on 2024-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebForm', '0015_passwordcode_email_passwordcode_generation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordcode',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
